### ISSUE TITLE
Menu里内嵌SubMenu是鼠标滑动较慢整个Menu会关闭

### ISSUE THREAD

**Issue by chern1992** [tinper-bee/bee-menus#3]
如图所示：
[https://hbimg.huabanimg.com/45427a1806e59148e9cabd289490be1ab4e1ca362555-mmfjMZ_fw658]()
鼠标慢慢滑过划线区域，整个menu就自动关闭了
代码如下
`<NCSubMenu title={<span>表格</span>}>
          <Item key="0">表格大小</Item>
          <NCSubMenu key="sub1" title={ <span>追加</span> }>
            <NCMenu.Item key="1row">整行</NCMenu.Item>
            <NCMenu.Item key="1col">整列</NCMenu.Item>
          </NCSubMenu>`

**Comment by yangchch6** [comment]
- bee-menus@2.0.7
    - [Fixbug]解决鼠标缓慢移动时，横向菜单消失的问题
